CREATE TABLE eventTypeCategory
(
    id number GENERATED BY DEFAULT AS IDENTITY START WITH 1 INCREMENT BY 1 PRIMARY KEY,
    eventType varchar2(40)
);
INSERT INTO eventTypeCategory
VALUES (0, 'NA');

CREATE TABLE userAgentNameCategory
(
    id number GENERATED BY DEFAULT AS IDENTITY START WITH 1 INCREMENT BY 1 PRIMARY KEY,
    userAgentName varchar2(60),
    userAgentVersion varchar2(60)
);
INSERT INTO userAgentNameCategory
VALUES (0, 'NA', 'NA');

CREATE TABLE userAgentFamilyCategory
(
    id number GENERATED BY DEFAULT AS IDENTITY START WITH 1 INCREMENT BY 1 PRIMARY KEY,
    userAgentFamily varchar2(60)
);
INSERT INTO userAgentFamilyCategory
VALUES (0, 'NA');

CREATE TABLE userAgentVendorCategory
(
    id number GENERATED BY DEFAULT AS IDENTITY START WITH 1 INCREMENT BY 1 PRIMARY KEY,
    userAgentVendor varchar2(60)
);
INSERT INTO userAgentVendorCategory
VALUES (0, 'NA');

CREATE TABLE userAgentTypeCategory
(
    id number GENERATED BY DEFAULT AS IDENTITY START WITH 1 INCREMENT BY 1 PRIMARY KEY,
    userAgentType varchar2(60)
);
INSERT INTO userAgentTypeCategory
VALUES (0, 'NA');

CREATE TABLE userAgentDeviceCategory
(
    id number GENERATED BY DEFAULT AS IDENTITY START WITH 1 INCREMENT BY 1 PRIMARY KEY,
    userAgentDevice varchar2(60)
);
INSERT INTO userAgentDeviceCategory
VALUES (0, 'NA');

CREATE TABLE userAgentOsFamilyCategory
(
    id number GENERATED BY DEFAULT AS IDENTITY START WITH 1 INCREMENT BY 1 PRIMARY KEY,
    userAgentOsFamily varchar2(40)
);
INSERT INTO userAgentOsFamilyCategory
VALUES (0, 'NA');

CREATE TABLE userAgentOsVendorCategory
(
    id number GENERATED BY DEFAULT AS IDENTITY START WITH 1 INCREMENT BY 1 PRIMARY KEY,
    userAgentOsVendor varchar2(60)
);
INSERT INTO userAgentOsVendorCategory
VALUES (0, 'NA');

CREATE TABLE projectIdCategory
(
    id number GENERATED BY DEFAULT AS IDENTITY START WITH 1 INCREMENT BY 1 PRIMARY KEY,
    projectId varchar2(60)
);
INSERT INTO projectIdCategory
VALUES (0, 'NA');

CREATE TABLE sub_projectIdCategory
(
    id number GENERATED BY DEFAULT AS IDENTITY START WITH 1 INCREMENT BY 1 PRIMARY KEY,
    sub_projectId varchar2(60)
);
INSERT INTO sub_projectIdCategory
VALUES (0, 'NA');

CREATE TABLE currencySymbolCategory
(
    id number GENERATED BY DEFAULT AS IDENTITY START WITH 1 INCREMENT BY 1 PRIMARY KEY,
    currencySymbol varchar2(20)
);
INSERT INTO currencySymbolCategory
VALUES (0, 'NA');

CREATE TABLE localeLanguageCategory
(
    id number GENERATED BY DEFAULT AS IDENTITY START WITH 1 INCREMENT BY 1 PRIMARY KEY,
    localeLanguage varchar2(20)
);
INSERT INTO localeLanguageCategory
VALUES (0, 'NA');

CREATE TABLE locale_nameCategory
(
    id number GENERATED BY DEFAULT AS IDENTITY START WITH 1 INCREMENT BY 1 PRIMARY KEY,
    locale_name varchar2(20)
);
INSERT INTO locale_nameCategory
VALUES (0, 'NA');