SELECT COUNT(*)
FROM (SELECT COUNT(*)
      FROM facts
      GROUP BY trunc(TIME_STAMP, 'hh24'), REMOTEHOST, EVENTTYPE, USERAGENTNAMEVERSION, USERAGENTFAMILY,
               USERAGENTVENDOR, USERAGENTTYPE, USERAGENTDEVICECATEGORY, USERAGENTOSFAMILY, USERAGENTOSVENDOR,
               PROJECTID, SUB_PROJECTID, CURRENCYSYMBOL, LOCALELANGUAGE, LOCALE_NAME);